source ~/.zgen/zgen.zsh

if ! zgen saved; then
  PLUGS=$HOME/.zsh_custom

  zgen oh-my-zsh
  zgen loadall <<EOF
    $ZGEN_OH_MY_ZSH_REPO plugins/git
    $ZGEN_OH_MY_ZSH_REPO plugins/git-extras
    $ZGEN_OH_MY_ZSH_REPO plugins/gitfast
    $ZGEN_OH_MY_ZSH_REPO plugins/safe-paste
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-completions

    $PLUGS/plugins/go
    $PLUGS/plugins/fzf
    $PLUGS/plugins/defaults

    $PLUGS/themes/hugelgupf
EOF

  if [ -d $PLUGS/plugins/snowflake ]; then
    zgen load $PLUGS/plugins/snowflake
  fi

  zgen save
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
